name: flutter_page_tranzitionz
description: A set of Page Route Transitions for simple and easy animations between different screens. Inspired by other packages on pub.dev.
version: 1.0.0
repository: https://github.com/mj12358/flutter-page-transitions

environment:
  sdk: ">=2.19.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
